services:
    lavalink:
        image: ghcr.io/lavalink-devs/lavalink:latest
        container_name: lavalink
        restart: unless-stopped
        environment:
            - _JAVA_OPTIONS=-Xmx1G
            - SERVER_PORT=2333
            - LAVALINK_SERVER_PASSWORD=youshallnotpass
        ## Use "./" if you want to create a mount from your current directory (where docker-compose.yml is located)
        ## Read more about binding volumes: https://docs.docker.com/storage/bind-mounts/
        volumes:
            - type: bind
              source: ./application.yml
              target: /opt/Lavalink/application.yml
        networks:
            - vocard
        expose:
            - "2333"

    ## You can selfhost MongoDB. Just uncomment lines starting with single "#" below.
    # mongo:
    #     image: mongo:latest
    #     container_name: mongo
    #     restart: unless-stopped
    #     volumes:
    #         - type: bind
    #           source: ./data/mongo/db
    #           target: /data/db
    #         - type: bind
    #           source: ./data/mongo/conf
    #           target: /data/configdb
    #     environment:
    #         - MONGO_INITDB_ROOT_USERNAME=admin
    #         - MONGO_INITDB_ROOT_PASSWORD=admin
    #     expose:
    #         - "27017"
    #     networks:
    #         - vocard
    #     command: ["mongod", "--oplogSize=1024", "--wiredTigerCacheSizeGB=1", "--auth", "--noscripting"]

    vocard:
        container_name: vocard
                 
        ## Pull Docker image from GitHub
        image: ghcr.io/chocomeow/vocard:v2.6.8

        ## Uncomment to build image from Dockerfile
        #build:
            #dockerfile: ./Dockerfile

        ## Use "./" if you want to create a mount from your current directory (where docker-compose.yml is located)
        ## Read more about binding volumes: https://docs.docker.com/storage/bind-mounts/
        volumes:
            - type: bind
              source: ./settings.json
              target: /app/settings.json
        depends_on:
            lavalink:
                condition: service_started
            # mongo:
            #     condition: service_started
        networks:
            - vocard
        ## Uncomment if web dashboard is going to be used. <your_available_server_port>:5000 
        #ports:
        #    - 5000:5000

networks:
    vocard:
        name: vocard
